#!/usr/bin/env python3
"""
bridge.py — Gemini (Strategic Architect) <-> Claude Code (Execution Engineer)
closed-loop development pipeline.

!! DANGER — READ BEFORE RUNNING !!
This script invokes the local `claude` CLI with permission prompts fully
bypassed (`--dangerously-skip-permissions`), executing instructions that
were themselves generated by another model (Gemini) and never reviewed by
a human. Each cycle can run arbitrary shell commands and modify/delete
arbitrary files on this machine. There is no human checkpoint between
"Gemini writes a plan" and "Claude Code executes it".

Safety nets that ARE in place (do not remove):
  - A hard iteration cap (--max-iterations, default 25).
  - A STOP file (storage/STOP) you can create at any time to halt the loop
    cleanly after the current cycle finishes.
  - Ctrl+C (SIGINT) triggers a graceful shutdown after the current cycle.
  - Every cycle's blueprint, stdout/stderr, and exit code are logged to
    storage/bridge.log and storage/cycles/ for after-the-fact audit.

Nothing else is sandboxed. Run this only in a disposable environment or a
directory you have backed up / committed to git, and only against a
`master_profile.md` you trust.

Setup:
    pip install google-genai
    export GEMINI_API_KEY="..."      # https://aistudio.google.com/apikey

Usage:
    python3 bridge.py
    python3 bridge.py --max-iterations 10 --interval 5
    python3 bridge.py --max-iterations 0   # 0 = unbounded, STOP file / Ctrl+C only
"""

from __future__ import annotations

import argparse
import asyncio
import datetime
import shutil
import signal
import sys
from pathlib import Path

from google import genai

ROOT = Path(__file__).resolve().parent
STORAGE = ROOT / "storage"
CYCLES_DIR = STORAGE / "cycles"
MASTER_PROFILE = STORAGE / "master_profile.md"
NEXT_SPRINT = STORAGE / "next_sprint.md"
LOG_FILE = STORAGE / "bridge.log"
STOP_FILE = STORAGE / "STOP"

ARCHITECT_MODEL = "gemini-2.5-pro"
CLAUDE_BIN = "claude"

# Keep the feedback context bounded so it doesn't grow unboundedly across
# cycles and blow past Gemini's context window / rack up cost.
MAX_CONTEXT_CHARS = 20_000
MAX_LOG_CHARS_PER_CYCLE = 8_000


def log(message: str) -> None:
    timestamp = datetime.datetime.now().isoformat(timespec="seconds")
    line = f"[{timestamp}] {message}"
    print(line, flush=True)
    with LOG_FILE.open("a", encoding="utf-8") as f:
        f.write(line + "\n")


def truncate(text: str, limit: int) -> str:
    if len(text) <= limit:
        return text
    marker = "\n...[truncated]...\n"
    keep = limit - len(marker)
    head = text[: keep // 2]
    tail = text[-(keep - keep // 2):]
    return head + marker + tail


def get_architect_instruction(client: genai.Client, context: str) -> str:
    """Ask Gemini (the Strategic Architect) for the next step-by-step
    code blueprint, given the master profile and current development state."""
    if not MASTER_PROFILE.exists():
        raise FileNotFoundError(
            f"{MASTER_PROFILE} is missing. Create it before running bridge.py."
        )
    profile = MASTER_PROFILE.read_text(encoding="utf-8")

    prompt = f"""You are the Strategic Architect in an automated development pipeline.
An Execution Engineer (Claude Code) will carry out your instructions verbatim,
with no human review in between. Because of that, your blueprint must be
precise, safe, and scoped to one concrete increment of work.

# Master Profile
{profile}

# Current Development State (build/test logs, prior cycle output)
{context if context.strip() else "(This is the first cycle. There is no prior state yet.)"}

# Your task
Produce the next step-by-step code blueprint for the Execution Engineer.
Requirements for your response:
- Be concrete: name exact files to create/edit and what the code should do.
- Scope it to ONE small, testable increment — not the whole project.
- Include how to verify the change (e.g. which command to run/tests to add).
- Do not include destructive shell commands (no rm -rf, force pushes, etc.).
- If the prior state shows a failure, diagnose it and fix it before adding
  anything new.

Respond with ONLY the blueprint, formatted in Markdown, ready to hand to the
Execution Engineer as-is.
"""

    response = client.models.generate_content(
        model=ARCHITECT_MODEL,
        contents=prompt,
    )
    text = (response.text or "").strip()
    if not text:
        raise RuntimeError("Gemini returned an empty blueprint.")
    return text


async def run_execution_agent(blueprint: str) -> tuple[str, int]:
    """Write Gemini's blueprint to storage/next_sprint.md and invoke Claude
    Code to execute it, with permission prompts bypassed. Returns the
    combined stdout/stderr log and the process exit code."""
    NEXT_SPRINT.write_text(blueprint, encoding="utf-8")

    if shutil.which(CLAUDE_BIN) is None:
        raise FileNotFoundError(
            f"`{CLAUDE_BIN}` was not found on PATH. Install/expose the Claude "
            "Code CLI before running bridge.py."
        )

    instruction = (
        "execute the instructions exactly as written in storage/next_sprint.md"
    )

    log(f"Invoking `{CLAUDE_BIN}` in headless mode with permissions bypassed...")
    process = await asyncio.create_subprocess_exec(
        CLAUDE_BIN,
        "-p",
        instruction,
        "--dangerously-skip-permissions",
        cwd=str(ROOT),
        stdout=asyncio.subprocess.PIPE,
        stderr=asyncio.subprocess.STDOUT,
    )

    output_chunks: list[bytes] = []
    assert process.stdout is not None
    async for line in process.stdout:
        output_chunks.append(line)
        sys.stdout.write(line.decode(errors="replace"))
        sys.stdout.flush()

    returncode = await process.wait()
    combined_output = b"".join(output_chunks).decode(errors="replace")
    return combined_output, returncode


def save_cycle_artifacts(
    iteration: int, blueprint: str, output: str, returncode: int
) -> None:
    CYCLES_DIR.mkdir(parents=True, exist_ok=True)
    stamp = f"{iteration:04d}"
    (CYCLES_DIR / f"{stamp}_blueprint.md").write_text(blueprint, encoding="utf-8")
    (CYCLES_DIR / f"{stamp}_output.log").write_text(
        f"exit_code={returncode}\n\n{output}", encoding="utf-8"
    )


async def main_loop(max_iterations: int, interval_seconds: float) -> None:
    api_key_client = genai.Client()  # reads GEMINI_API_KEY from env

    stop_requested = asyncio.Event()

    def request_stop(*_args) -> None:
        log("SIGINT received — will stop after the current cycle finishes.")
        stop_requested.set()

    loop = asyncio.get_running_loop()
    try:
        loop.add_signal_handler(signal.SIGINT, request_stop)
    except NotImplementedError:
        # add_signal_handler isn't available on some platforms (e.g. Windows).
        signal.signal(signal.SIGINT, lambda *_: request_stop())

    context = ""
    iteration = 0

    log(
        "Bridge starting. max_iterations="
        f"{max_iterations or 'unbounded'} interval={interval_seconds}s"
    )
    log(f"Create {STOP_FILE.relative_to(ROOT)} at any time to stop cleanly.")

    while True:
        iteration += 1
        if max_iterations and iteration > max_iterations:
            log(f"Reached max_iterations={max_iterations}. Stopping.")
            break
        if STOP_FILE.exists():
            log(f"STOP file detected at {STOP_FILE}. Stopping before cycle {iteration}.")
            break

        log(f"--- Cycle {iteration}: requesting blueprint from {ARCHITECT_MODEL} ---")
        try:
            blueprint = get_architect_instruction(api_key_client, context)
        except Exception as exc:  # architect failures shouldn't crash the loop silently
            log(f"Architect call failed: {exc}")
            break

        log(f"Blueprint received ({len(blueprint)} chars). Handing off to Claude Code.")
        try:
            output, returncode = await run_execution_agent(blueprint)
        except Exception as exc:
            log(f"Execution agent failed: {exc}")
            break

        save_cycle_artifacts(iteration, blueprint, output, returncode)
        log(f"Cycle {iteration} finished with exit code {returncode}.")

        context = truncate(
            f"## Cycle {iteration} blueprint\n{blueprint}\n\n"
            f"## Cycle {iteration} execution output (exit={returncode})\n"
            f"{truncate(output, MAX_LOG_CHARS_PER_CYCLE)}",
            MAX_CONTEXT_CHARS,
        )

        if stop_requested.is_set():
            log("Stop requested. Not starting another cycle.")
            break

        if interval_seconds > 0:
            await asyncio.sleep(interval_seconds)

    log("Bridge stopped.")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--max-iterations",
        type=int,
        default=25,
        help="Hard cap on cycles. Set to 0 for unbounded (STOP file / Ctrl+C only). Default: 25.",
    )
    parser.add_argument(
        "--interval",
        type=float,
        default=3.0,
        help="Seconds to wait between cycles. Default: 3.",
    )
    return parser.parse_args()


if __name__ == "__main__":
    args = parse_args()
    STORAGE.mkdir(parents=True, exist_ok=True)
    try:
        asyncio.run(main_loop(args.max_iterations, args.interval))
    except KeyboardInterrupt:
        log("Interrupted. Exiting.")
